spring:
  application:
    name: leave-service
  profiles:
    active: dev
  # environment: dev|test|prod
logging:
  config: classpath:logback_${spring.profiles.active}.xml
  level:
    #    root: DEBUG
    root: INFO

---
server:
  port: 8089
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://localhost:3306/leave?characterEncoding=utf8&useSSL=false
    username: root
    password: 999999
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
      #不會產生資料表
      #ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
        order_insert: true    //配置批量新增
        order_update: true    //配置批量修改
        jdbc:
          batch_size: 1000
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: false
    # MysqlDialect是比較早的配置,如果專案使用的是MySQL 5,最好使用MySQL5Dialect(不加此行導致資料庫無法建立表格)
    # 在 Hibernate 5.x 和更早版本中——方言org.hibernate.dialect.MySQLDialect適用於 MySQL 4.x 或更早版本。TYPE=MYISAM此方言生成的片段在 MySQL 4.0 中已棄用，並在 5.5 中刪除
    database-platform: org.hibernate.dialect.MySQL5Dialect
    servlet:
      multipart:
        max-file-size: 20MB
        max-request-size: 20MB

---
server:
  port: 8089
spring:
  profiles: prod

  datasource:
    url: jdbc:mysql://ip:port/leave?characterEncoding=utf8&useSSL=false
    username: root
    password: 999999
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
#      ddl-auto: update
      #不會產生資料表
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
        order_insert: true    //配置批量新增
        order_update: true    //配置批量修改
        jdbc:
          batch_size: 1000
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: false
    #MysqlDialect是比較早的配置,如果專案使用的是MySQL 5,最好使用MySQL5Dialect(不加此行導致資料庫無法建立表格)
    database-platform: org.hibernate.dialect.MySQL5Dialect
    servlet:
      multipart:
        max-file-size: 20MB
        max-request-size: 20MB