spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ip:5432/leave
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
#  main:#    allow-bean-definition-overriding: true